### PR TITLE
Support for Just Works pairing

### PR DESCRIPTION
**Pull request by bluetooth-mdw**
Redid this from scratch... easier (for me) than sorting out merge conflicts.

### CODE REVIEW

**Comment by bluetooth-mdw** [comment]
Supercedes https://github.com/lancaster-university/microbit-dal/pull/154

**Comment by finneyj** [comment]
Thanks @bluetooth-mdw. Looks great - merging.

**Comment by pelikhan** [comment]
Is this new pairing documented?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by finneyj** [comment]
@bluetooth-mdw? I know you're busy, but can you please add a small section into the Bluetooth section of microbit-docs to outline this when you have a moment?

**Comment by bluetooth-mdw** [comment]
Yes, it's already on one of my lists to which other lists point :-)

**Comment by finneyj** [comment]
thanks. Sounds like you need an mbuf... or maybe an oct-tree. :-)

**Comment by bluetooth-mdw** [comment]
...or a willing and able minion to boss around. What's that like?

**Pull request merged**
