### PR TITLE
Added suport for Just Works pairing in MicroBitBLEManager.cpp

### PR DESCRIPTION
**Pull request by bluetooth-mdw**

### CODE REVIEW

**Comment by pelikhan** [comment]
Sounds exciting, more details?

**Comment by bluetooth-mdw** [comment]
Hi Peli

Bluetooth specifies various "association models" which are alternate ways in which authentication is or is not used in the pairing process. We currently use passkey authentication requiring the 6 digit random number to be displayed on micro:bit and entered on the other device, typically a smart phone. This is a secure approach to pairing but not the easiest for some users.

Just Works pairing.... just works.... with no user interaction required at all. So very simple UX.

Once you've paired, security is the same regardless of how you paired.

Cheers

Martin

**Comment by jamesadevine** [comment]
Sorry, on mobile.

I note you have added a deletion to CCS.S, could you fix that Martin?

James.

On 3 Jun 2016, at 14:10, Martin Woolley <notifications@github.com<mailto:notifications@github.com>> wrote:

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/lancaster-university/microbit-dal/pull/153

Commit Summary

  *   Added suport for Just Works pairing in MicroBitBLEManager.cpp

File Changes

  *   M inc/core/MicroBitConfig.h<https://github.com/lancaster-university/microbit-dal/pull/153/files#diff-0> (10)
  *   D source/asm/CortexContextSwitch.s<https://github.com/lancaster-university/microbit-dal/pull/153/files#diff-1> (293)
  *   M source/bluetooth/MicroBitBLEManager.cpp<https://github.com/lancaster-university/microbit-dal/pull/153/files#diff-2> (9)

Patch Links:

  *   https://github.com/lancaster-university/microbit-dal/pull/153.patch
  *   https://github.com/lancaster-university/microbit-dal/pull/153.diff

**Comment by bluetooth-mdw** [comment]
Not deliberately! :-)

**Comment by martinwork** [comment]
Did you mean to change the defaults in MicroBitConfig.h?

**Comment by jamesadevine** [comment]
That too!

James.

On 3 Jun 2016, at 14:45, Martin Williams <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you mean to change the defaults in MicroBitConfig.h?

**Comment by finneyj** [comment]
Martin is working up a cleaner independent PR to come in shortly, so closing this one off... :-)

**Pull request closed without merging**
