### PR TITLE
Move PWM code into HAL and factor out debouncing from MicroBitButton

### PR DESCRIPTION
**Pull request by markshannon**
A first step to fixing https://github.com/lancaster-university/microbit-dal/issues/40
Move PWM into `hal/` sub folder.
Separate out the debouncing aspect of `MicroBitButton` from the event signalling and move it into the HAL.

### CODE REVIEW

**Comment by jamesadevine** [comment]
Superseded by recent changes to the DAL.

Closing.

**Comment by markshannon** [comment]
It hasn't been superseded. 
The MicroBitButton is still coupled to the MicroBitSystemTimer, so we can't use it independently.

**Comment by finneyj** [comment]
Hello @markshannon.

Why is that a problem for you? MicrobitSystemTimer is just a lightweight multiplexed Ticker, so we can save some RAM (lots of components need a sense of time, and Ticker instances are quite expensive in terms RAM).

I thought it was the fiber scheduler and message bus that was causing the problems?

**Comment by markshannon** [comment]
But why depend on it at all?

**Comment by finneyj** [comment]
oh, that's for the debounce logic and event timers (to detect a button HOLD for example). You can't debounce without some notion of the passage of time.

**Comment by markshannon** [comment]
The `DebouncedPin` class in this PR has a `tick` method, but does not enforce the use of any particular timer.
So, why does depend `MicrobitButton.cpp` depend on "MicroBitSystemTimer.h"?

**Comment by finneyj** [comment]
Iin my mind this is a case of simple encapsulation - the timer is an internal requirement for the component so it takes care of it transparently. As a periodic timer is a common requirement for quite a few components, having a multiplexed clock source makes sense to reduce RAM overhead. I'm still not clear what the problem is here.

It feels like we're getting a bit caught up on a specific detail here though. Both microbit-dal and micropython have moved on considerably since we last talked on this thread. Would be not be better off discussing things afresh from a top down perspective, then go from there?

i.e. now we have a version of microbit-dal with a set of components that run without the scheduler, memory manager and messagebus, ble, etc, perhaps we should first be discussing the architecture for this to be best utilized by micropython?

**Comment by finneyj** [comment]
what thinks @markshannon? Want to join forces on this?

Broadening our discussion could give us better solutions - e.g. if you have issues with timers, then a bit of work aligning on MicroBitSystemTimer would provide support for a whole set of components transparently?

**Comment by markshannon** [comment]
@finneyj Sounds like a good idea, but I'm going to be *really* busy until early June. So progress will be slow to non-existent on my side until then.

**Comment by finneyj** [comment]
cool. No worries @markshannon - totally understand. We're all working this around our other responsibilities... Just give me a shout when you have time to do a bit of design.

**Comment by ntoll** [comment]
Perhaps it would be useful to get "brains in the same room" sometime in June/July? I always find face-to-face meetings result in good things.

**Comment by finneyj** [comment]
Absolutely - co-design always best done around a whiteboard, with as much coffee as can be feasibly consumed!

Not sure where you guys are based, but we'd happily host if you'd like to visit.

**Comment by ntoll** [comment]
I'm in Northampton (actually Towcester, but close enough), @markshannon is relatively close by in Oxford (i.e. I could give him a lift) and @dpgeorge is in Cambridge. Perhaps we could wangle something half way (approximately just north of Brum) so everyone could do it in a day over a weekend..?

**Comment by markshannon** [comment]
In June/July I'll be in San Francisco, so it might be awkward to pop over to Cambridge :smile:

**Comment by ntoll** [comment]
Ahh... well, at the start of June I'll be in Portland for PyCon. ;-) See you there! @finneyj why not come to Portland? ;-)

**Comment by mmoskal** [comment]
Very good coffee and fine craft beer. And the only chance to see the place where young people go to retire before it is completely overrun by climate change refugees from California! ;)

**Pull request closed without merging**
