### PR TITLE
Bugfix 289

### LINKED ISSUE #289: MicroBitIOPinService truncates analogue input values above 255
onDataRead and idleTick both do this: 

uint8_t value;
value = io.pin[i].getAnalogValue(); 

So values above 255 get reported mod 256.

### PR DESCRIPTION
**Pull request by finneyj**
Fix #289

### CODE REVIEW

**Comment by cpseager** [comment]
LGTM. Whilst working on this is it possible to rename the really confusing isInput and isOutput as well?

These are actually nothing to do with a DDR as both the name and comments suggests - this really confused me when first using them. Setting/clearing the bit does **not** configure the pin as an input or as an output! Setting the pin simply 'activates' that pin as an input that is read rather than ignored..

isInput should be something like isInputActive

isOutput should be something like isInputInactive

**Comment by finneyj** [comment]
@cpseager  sure - done.

**Comment by finneyj** [comment]
@martinwork Anything you'd like to add?

**Comment by cpseager** [comment]
@finneyj Thanks. Update line 49 comment too?

**Comment by martinwork** [comment]
Thanks @finneyj . Creating updateBLEInputs was a good idea. However this made me notice that onDataRead is calling notify. I'm far from sure and I am not in a position to easily test this right now, but I suspect calling notify is not appropriate inside the ReadAuthorization callback, because a read is already underway.

How quickly is this fix likely to make it to PXT?

**Comment by finneyj** [comment]
@martinwork Thanks. 

I think this is ok.  Recall that the notify() call doesn't necessarily raise a notification, but records the new value of the characteristic flags with the BLE stack that a notification should be scheduled if appropriate.  It worked in my tests anyway (I tested both reads and notify via the Nordic diagnostic tools).

Once we merge it'll go into the next release and pretty much straight into PXT (usually a few days lag to beta, then trickle in live). I want to merge in the compass and FS bug fixes to next release too.

**Comment by finneyj** [comment]
Thanks all - updated and merged

**Pull request merged**
