### PR TITLE
Delayed disconnecting after pairing complete by 500ms

### PR DESCRIPTION
**Pull request by bluetooth-mdw**
Ref: https://github.com/lancaster-university/microbit-dal/issues/254

### CODE REVIEW

**Comment by finneyj** [comment]
Looks good to me @bluetooth-mdw. Happy to merge this.

I'll just leave open a little while in case others spot anything, but we'll merge before next tagged release.

**Comment by martinwork** [comment]
Forget I asked that last question!

**Comment by finneyj** [comment]
what question? :-)

You know, I think github should have a "right to be forgotten" feature for such inevitable moments!

**Comment by bluetooth-mdw** [comment]
+1

:-)

**Comment by jamesadevine** [comment]
@bluetooth-mdw Did you manage to test iOS to check that behaviour is the same?

**Comment by martinwork** [comment]
Thanks! But I'm inclined to stick by the first bit... That fiber_remove_idle_component will mean idleTick is only called once and disconnect will never happen.

**Comment by jamesadevine** [comment]
@martinwork I agree, @bluetooth-mdw the `fiber_remove_idle_component` needs to be moved into the if statement as well!

**Comment by finneyj** [comment]
yes - quite right. #RightToBeRemembered !

**Comment by bluetooth-mdw** [comment]
<blush>

**Comment by finneyj** [comment]
Thanks @bluetooth-mdw! Looking pretty uncontroversial now i think. Thanks for the additional testing too.

**Comment by bluetooth-mdw** [comment]
"uncontroversial" means "less rubbish", right? :-)

**Comment by finneyj** [comment]
@bluetooth-mdw - right! :-)

**Pull request merged**
