### PR TITLE
MicroBitLightSensor

### PR DESCRIPTION
**Pull request by jamesadevine**
A light sensor that interleaves with the display.

Open for comments!

### CODE REVIEW

**Comment by zfm076** [comment]
> @dpgeorge :
> 
> ```
> void app_main()
> {
> 
>     uBit.display.disable();
> 
>     MicroBitLightSensor* ls = new MicroBitLightSensor();
> 
>     while(1)
>     {
>         MicroBitEvent(MICROBIT_ID_DISPLAY, MICROBIT_DISPLAY_EVT_LIGHT_SENSE);
>         uBit.sleep(100);
>         uBit.serial.printf("lightlevel: %d\r\n", ls->read());
>     }
> }
> ```
Compilation error prompt:Error:
**No instance of constructor "MicroBitLightSensor::MicroBitLightSensor"  matches the argument list in "main.cpp"**

code:
```
#include "MicroBit.h"

MicroBitDisplay display;
MicroBit uBit;

int main()
{
    uBit.init();
    uBit.display.disable();

    MicroBitLightSensor* ls = new MicroBitLightSensor();

    while(1)
    {
        MicroBitEvent(MICROBIT_ID_DISPLAY, MICROBIT_DISPLAY_EVT_LIGHT_SENSE);
        uBit.sleep(100);
        uBit.serial.printf("lightlevel: %d\r\n", ls->read());
    }
}

```

**Comment by dpgeorge** [comment]
@zfm076 I'm afraid you'll need to ask someone else (or ask somewhere else) for help with that.

**Comment by martinwork** [comment]
Try this?
`MicroBitLightSensor* ls = new MicroBitLightSensor( microbitMatrixMap);
`

**Comment by zfm076** [comment]
> @zfm076 I'm afraid you'll need to ask someone else (or ask somewhere else) for help with that.

I found the solution.Thank you.

**Comment by zfm076** [comment]
> Try this?
> `MicroBitLightSensor* ls = new MicroBitLightSensor( microbitMatrixMap); `
Thank you. I used another API to get the LightLevel,  but I don't know what the impact is on the display, is there any hidden danger? as follows:
```
#include "MicroBit.h"
MicroBit uBit;
uint8_t lightLevel;

void lightLevelReady(MicroBitEvent) 
{
   lightLevel = uBit.display.readLightLevel();
   uBit.serial.send(lightLevel);
   uBit.serial.send("\r\n");
}

int main()
{
   uBit.init();
   uBit.messageBus.listen(MICROBIT_ID_DISPLAY, MICROBIT_DISPLAY_EVT_LIGHT_SENSE, 
   lightLevelReady);
   uBit.display.readLightLevel();
   while (1) 
   {
       fiber_sleep(20);
   }
}
```

**Comment by martinwork** [comment]
uBit.display.readLightLevel() is the usual way to read the light level, while keeping the display enabled. This uses a special display mode, which alters the frequency of the systemTick and conflicts with getAnalogValue().

MICROBIT_DISPLAY_EVT_LIGHT_SENSE is triggered by the display every 20ms to start update of the value returned by readLightLevel(), so it's not really a light-level-ready event. I can't think of any problems that listening to it would cause in this example. Three update events are needed to read all the channels. After the very first call to readLightLevel(), the value will take 60-80ms to ramp up from zero. Maybe start with

```
   uBit.init();
   uBit.display.readLightLevel();
   fiber_sleep(80);
   uBit.messageBus.listen(MICROBIT_ID_DISPLAY, MICROBIT_DISPLAY_EVT_LIGHT_SENSE, 
   lightLevelReady);
```

**Comment by zfm076** [comment]
> uBit.display.readLightLevel() is the usual way to read the light level, while keeping the display enabled. This uses a special display mode, which alters the frequency of the systemTick and conflicts with getAnalogValue().
> 
> MICROBIT_DISPLAY_EVT_LIGHT_SENSE is triggered by the display every 20ms to start update of the value returned by readLightLevel(), so it's not really a light-level-ready event. I can't think of any problems that listening to it would cause in this example. Three update events are needed to read all the channels. After the very first call to readLightLevel(), the value will take 60-80ms to ramp up from zero. Maybe start with
> 
> ```
>    uBit.init();
>    uBit.display.readLightLevel();
>    fiber_sleep(80);
>    uBit.messageBus.listen(MICROBIT_ID_DISPLAY, MICROBIT_DISPLAY_EVT_LIGHT_SENSE, 
>    lightLevelReady);
> ```

Thank you. Except this .Is there any other way to get the LightLevel value?

**Comment by martinwork** [comment]
That's what I thought you were trying to do in your original code! I haven't tried it, but with the display disabled you may be able to use MicroBitLightSensor directly so that you can also read other analogue pins. Or write code that does the same thing as MicroBitLightSensor and reads other pins...

**Comment by zfm076** [comment]
> That's what I thought you were trying to do in your original code! I haven't tried it, but with the display disabled you may be able to use MicroBitLightSensor directly so that you can also read other analogue pins. Or write code that does the same thing as MicroBitLightSensor and reads other pins...

Thank you . I have another question:I want to send sensor data with a timed interrupt(50ms).But,It not work.Can you take a look at it for me?Thank.

1: 
Defined MY_Microbit.h file:
```
class MY_MicroBit
{
  private:
    MicroBit *uBit; //Define a pointer
    Timeout Send_Sensor_Interrupt; //class Timeout Defined in mbed-classic/api

  public:
    MY_MicroBit(MicroBit *uBit);
    void Send_Sensor_Data(); 
};
```
2:
Defined MY_Microbit.cpp file:
```
#include "MY_MicroBit.h"
void HWJ_MicroBit::Send_Sensor_Data()
{
   this->uBit->serial.send(456); //The debug did not run here ，So No interruption occurred.
   this->uBit->serial.send( this->uBit->thermometer.getTemperature()  );
}
HWJ_MicroBit::HWJ_MicroBit(MicroBit *MicroBit)
{
    this->uBit = MicroBit;
    this->uBit->serial.send(123); //Debugging can run here

    /*
       Interrupt 50ms call Send_Sensor_Data() function,
        I referred to the function ：void MicroBitLightSensor::startSensing(MicroBitEvent)
        analogTrigger.attach_us(this, &MicroBitLightSensor::analogReady, 
        MICROBIT_LIGHT_SENSOR_AN_SET_TIME);
   */
    Send_Sensor_Interrupt.attach_us(this, &HWJ_MicroBit::Send_Sensor_Data,50000);
}

```
3:main.cpp:

```
#include "MicroBit.h"
#include "MY_MicroBit.h"

MicroBit uBit; //Instantiate MicroBit class
uint8_t lightLevel;

void lightLevelReady(MicroBitEvent) 
{
   lightLevel = uBit.display.readLightLevel();
   uBit.serial.send(lightLevel);
   uBit.serial.send("\r\n");
}

int main()
{
   uBit.init();
   uBit.messageBus.listen(MICROBIT_ID_DISPLAY, MICROBIT_DISPLAY_EVT_LIGHT_SENSE, 
   lightLevelReady);
   uBit.display.readLightLevel();
 
  MY_MicroBit my_uBit(&uBit); //Instantiate a MY_MicroBit class
   while (1) 
   {
   }
  release_fiber();
}
```

**Comment by martinwork** [comment]
Is it stuck in the while (1), do nothing loop? Try deleting that.

For a 50ms interval, maybe a DAL fiber would do the job:
https://www.instructables.com/id/BBC-Microbit-C-Getting-Started/

An Mbed Timeout will only call the function once. A Ticker is for repeated calls. In the documentation for Ticker, it lists things that you cannot do in the handler (just about everything!): https://os.mbed.com/docs/mbed-os/v5.15/apis/ticker.html.

**Comment by zfm076** [comment]
> Is it stuck in the while (1), do nothing loop? Try deleting that.
> 
> For a 50ms interval, maybe a DAL fiber would do the job:
> https://www.instructables.com/id/BBC-Microbit-C-Getting-Started/
> 
> An Mbed Timeout will only call the function once. A Ticker is for repeated calls. In the documentation for Ticker, it lists things that you cannot do in the handler (just about everything!): https://os.mbed.com/docs/mbed-os/v5.15/apis/ticker.html.

Thank you. That was very helpful!

But I tried to use  DAL fiber and it went Compilation error:  
error: no matching function for call to 'create_fiber(void (HWJ_MicroBit::*)())'  create_fiber(&HWJ_MicroBit::Send_Sensor_Data_fiber);

So,create_fiber() function Can't pass Class function pointer? if I want to create fiber for the function of a class and How can I modify it?

Code:
1:
Defined MY_Microbit.h file:

```
#include "MicroBit.h"
#include "mbed.h"

class MY_MicroBit
{
  private:
    MicroBit *uBit; //Define a pointer

  public:
    MY_MicroBit(MicroBit *uBit);
    void Send_Sensor_Data(); 
    void Send_Sensor_Data_fiber();
};
```
2:
Defined MY_Microbit.cpp file:

```
#include "MY_MicroBit.h"

void MY_MicroBit::Send_Sensor_Data() //Sending sensor data
{
   this->uBit->serial.send( this->uBit->thermometer.getTemperature()  );
}

void MY_MicroBit::Send_Sensor_Data_fiber() //fiber manipulation function
{
    while(1)
    {
        Send_Sensor_Data();  //Sending sensor data
        this->uBit->sleep(50); //Interval 50 ms
    }
}

MY_MicroBit::MY_MicroBit(MicroBit *MicroBit) // constructor function
{
    this->uBit = MicroBit;
    create_fiber( &MY_MicroBit::Send_Sensor_Data_fiber );  //Create fiber
}
```

3:main.cpp:

```
#include "MicroBit.h"
#include "MY_MicroBit.h"

MicroBit uBit; //Instantiate MicroBit class

int main()
{
   uBit.init();
   MY_MicroBit my_uBit(&uBit); //Instantiate a MY_MicroBit class
   release_fiber();
}

```

**Comment by martinwork** [comment]
Check the header for alternatives:
https://github.com/lancaster-university/microbit-dal/blob/2cff906f019944ae15d532157c1301c940f67862/inc/core/MicroBitFiber.h

**Comment by zfm076** [comment]
> Check the header for alternatives:
> https://github.com/lancaster-university/microbit-dal/blob/2cff906f019944ae15d532157c1301c940f67862/inc/core/MicroBitFiber.h

Thanks martinwork!
Today, I was testing the computer sending data to microbit，I found a strange question：
```
char Computer_send = [0xFF, 0x01 ,0x00 ,0x02 ,0x00 ,0xF8 ,0xFF]

#include "MicroBit.h"
MicroBit uBit;
int main()
{
    while(1)
   {
      while( uBit.serial.isReadable() )
     {
        uBit.serial.send( (char)uBit.serial.read(ASYNC) , SYNC_SLEEP );
      }
   }
  release_fiber();
}
```

My Computer send the Computer_send data to microbit,and then my Computer receives data:
[0xFF, 0x01 ,0x02 ,0xF8 ,0xFF]. I checked my computer display and sent 7 bytes.But only five bytes were received. Microbit don't save 0x00 ? or  0x00 not be sent?

**Comment by martinwork** [comment]
Creating an issue to ask a question would help make the answer more visible to others. Searching for previous similar issues is also a good idea.

**Comment by zfm076** [comment]
> Creating an issue to ask a question would help make the answer more visible to others. Searching for previous similar issues is also a good idea.

Thanks. I knew the problem and solved it.

**Pull request merged**
