### PR TITLE
Refactored Eddystone support, added UID frame type

### PR DESCRIPTION
**Pull request by bluetooth-mdw**
Refactored Eddystone support, introducing a new Eddystone class which separates the Eddystone message format from the more general responsibilities of the MicroBitBLEManager class. Hopefully the pattern paves the way for other beacon formats (e.g. iBeacon, AltBeacon) to be introduced via their own classes.

Made MicroBitBLEManager a bit more "singleton-like" with a getInstance() method.

Added support for the Eddystone UID frame type.

Example use:

```
char UID_NAMESPACE[] = {0x0E,0x67,0x47,0x04,0x42,0xD0,0x14,0x06,0xD5,0x83}; // sha-1 hash of "com.bittysoftware" 
char UID_INSTANCE[]  = {0x00 , 0x00, 0x00, 0x00, 0x00, 0x01};
const int8_t CALIBRATED_POWERS[] = {-49, -37, -33, -28, -25, -20, -15, -10};

uint8_t advertising = 0;
uint8_t tx_power_level = 6;

void startAdvertising() {
    uBit.bleManager.advertiseEddystoneUid(UID_NAMESPACE, UID_INSTANCE, CALIBRATED_POWERS[tx_power_level-1], false);
    uBit.bleManager.setTransmitPower(6);
    uBit.display.scroll("ADV");
    advertising = 1;
}

```

### CODE REVIEW

**Comment by bluetooth-mdw** [comment]
@Thomas101 I added to your excellent work fyi. I'm speaking at an event in a couple of weeks on "physical web", beacons etc and look forward to demonstrating with micro:bit UID beacons operating in my fake but portable museum (toy dinosaur included!).

Cheers

**Comment by finneyj** [comment]
thanks @bluetooth-mdw. This is a nice step forward toward more component based handling of BLE beacons services. Good stuff! 

Formatting of comment blocks in MicroBitBLEManager.h looks like it may have escaped your "Pretty Formatting" commit somehow though.

**Comment by finneyj** [comment]
@Thomas101 Can you see any issues with @bluetooth-mdw refactor?

**Comment by Thomas101** [comment]
This looks good @bluetooth-mdw! I agree definately looks like a nice step forwards and I don't see any issue with it.

Would be great to see some slides/dinosaur photos from your talk!

**Comment by bluetooth-mdw** [comment]
The dinosaur is notoriously camera shy but I'll try to distract it and grab a pic :-)

Thanks!

**Pull request merged**
