### PR TITLE
Exposed MICROBIT_BLE_SECURITY_LEVEL through config.json

### PR DESCRIPTION
**Pull request by bluetooth-mdw**
Exposed MICROBIT_BLE_SECURITY_LEVEL through config.json as new security_level property.

Note that to build a hex file with no pairing required, the open property should continue to be set to 1. No change there.

Usage Examples:

1. Just Works pairing
```
{
    "microbit-dal": {
        "bluetooth": {
            "enabled": 1,
            "pairing_mode": 1,
            "open": 0,
            "security_level": "SECURITY_MODE_ENCRYPTION_NO_MITM",
            "whitelist": 1,
            "advertising_timeout": 0,
            "tx_power": 0,
            "dfu_service": 0,
            "event_service": 0,
            "device_info_service": 1
        },
        "gatt_table_size": "0x700"
    }
}
```

2. Passkey pairing
```
{
    "microbit-dal": {
        "bluetooth": {
            "enabled": 1,
            "pairing_mode": 1,
            "open": 0,
            "security_level": "SECURITY_MODE_ENCRYPTION_WITH_MITM",
            "whitelist": 1,
            "advertising_timeout": 0,
            "tx_power": 0,
            "dfu_service": 0,
            "event_service": 0,
            "device_info_service": 1
        },
        "gatt_table_size": "0x700"
    }
}

### CODE REVIEW

**Comment by pelikhan** [comment]
What does this new security level do?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by bluetooth-mdw** [comment]
It lets you choose whether passkey pairing or "just works" pairing is to be required by the resultant firmware. Previously you had to change a constant defined in MicroBitConfig.h to achieve this. Now, all I've done is exposed the property in config.json which is consistent with other Bluetooth config properties and hopefully makes it easier to make the choice of pairing techniques (including no pairing required) available in tools like the fabulous PXT.

**Comment by bluetooth-mdw** [comment]
Bump. Is this going to be merged?

**Comment by finneyj** [comment]
thanks for the nudge @bluetooth-mdw. Looks great.

**Comment by pelikhan** [comment]
Release tag?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by finneyj** [comment]
Was hoping for a James' JMX glue to complement File System, but it's been a while... i'll tag rc5 as an interim for you today.

**Pull request merged**
