### PR TITLE
fix for issue #252: bug in MicroBitUARTService#read when buffer conta…

### PR DESCRIPTION
**Pull request by kartben**
…ins NULL character

Signed-off-by: Benjamin Cabé <benjamin@eclipse.org>

### CODE REVIEW

**Comment by martinwork** [comment]
Should the && operands be swapped as well, to avoid reading and discarding an extra character after len have been read?

**Comment by jamesadevine** [comment]
Yup, @martinwork . We really need a Stream abstraction, it's been on our todo list for a while. This is another place where the same broken logic has cropped up again, I suspect because it's been implemented across 3 different classes, and the first time it was caught the change wasn't applied here.

**Comment by kartben** [comment]
Good catch @martinwork. I updated the condition.

**Comment by kartben** [comment]
any plan to merge this?

**Comment by finneyj** [comment]
Apologies @kartben - my many hands are full as usual. :-)

Looks great, very happy to merge. Thanks for the patch.

**Pull request merged**
