### PR TITLE
Fix Bluetooth Logo

### PR DESCRIPTION
**Pull request by microbit-sam**

### CODE REVIEW

**Comment by finneyj** [comment]
he-he.... This one got past the @bluetooth-mdw brand police. ;)

thanks @microbit-sam.

**Comment by bluetooth-mdw** [comment]
Wait? What??? :-)

**Comment by finneyj** [comment]
tut tut @bluetooth-mdw.../ Bluetooth logo was the wrong way around. ;)

**Comment by bluetooth-mdw** [comment]
Do you mean the "graphic" displayed on the LED matrix? Or somewhere it's printed?

**Comment by finneyj** [comment]
yep - on the LED matrix during pairing.

**Comment by bluetooth-mdw** [comment]
When you looked at it, did you see satanic messages? Like with every 70s rock LP when played backwards?

**Comment by finneyj** [comment]
yeah, I felt an irresistible urge to plug my microbit in via USB and program it that way instead. ;)

**Comment by microbit-sam** [comment]
The logo I put in this PR is also crap, this commit should probably be the one used:
https://github.com/microbit-sam/microbit-dal/commit/f7f488728518f495f7cde7c21656bcaf929333c3

**Comment by bluetooth-mdw** [comment]
You've awoken the (pretend) brand police in me.  I think you may be non-compliant in a number of ways. It's not *quite* the right shade of blue for example. See https://www.bluetooth.com/develop-with-bluetooth/marketing-branding

;-)

**Comment by microbit-sam** [comment]
img_20180808_122422

**Comment by finneyj** [comment]
Looks great to me. Can you raise another PR for me to merge @microbit-sam?

**Pull request closed without merging**
